# Generated by Django 4.2.1 on 2023-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopword',
            name='word',
            field=models.CharField(max_length=20, unique=True, verbose_name='Stop Word'),
        ),
    ]
