# Generated by Django 4.2.1 on 2023-05-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stopword_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelgramUser',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram User ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Telegram Chat ID')),
                ('username', models.CharField(max_length=64, null=True, verbose_name='Telegram Username')),
                ('active', models.BooleanField(default=False, verbose_name='Status is it available to send message')),
            ],
            options={
                'verbose_name': 'Telegtam user',
                'verbose_name_plural': 'Telegtam users',
            },
        ),
    ]
