# Generated by Django 4.2.1 on 2023-05-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telgramuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelgramUser',
            new_name='TelegramUser',
        ),
    ]
