# Generated by Django 4.2.1 on 2023-05-31 03:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_telgramuser_telegramuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="stopword",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stopword",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "advert_id",
                    models.CharField(max_length=10, verbose_name="Advert name"),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advert",
                "verbose_name_plural": "Adverts",
            },
        ),
    ]
